/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.thomasbao.bytecode_analysis

import org.apache.bcel.classfile.ClassParser
import org.apache.bcel.Const
import org.apache.bcel.classfile.ConstantClass
import java.io.File

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main(args: Array<String>) {
    val filepath = args.first()
    println("Parsing file: ${filepath}")
    val classParser = ClassParser(filepath)
    val javaClass = classParser.parse()
    println("Parsed!")

    val constantPool = javaClass.constantPool
    constantPool.map { it as? ConstantClass }.filterNotNull().forEach {
      val classRef = constantPool.getConstantUtf8(it.nameIndex)
      println(classRef)
    }

}
